name: Stable

on:
  push:
    tags:
      - '*'

jobs:

  # Release on GitHub
  github-release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse changelog
        run: |
          START="## ${{ steps.vars.outputs.version }}"
          END="## [0-9]+.[0-9]+.[0-9]+|\$"
          grep -oPz "(?s)${START}.*?\n\K.*?(?=${END})" CHANGELOG.md > changelog.txt
          truncate -s-3 changelog.txt
          sed -i '1d' changelog.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
